/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PostRouteImport } from './routes/post'
import { Route as ProRouteImport } from './routes/pro'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SecretRouteImport } from './routes/secret'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorldRouteImport } from './routes/world'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as UHandleRouteImport } from './routes/u.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretRoute = SecretRouteImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/secret': typeof SecretRoute
  '/settings': typeof SettingsRoute
  '/world': typeof WorldRoute
  '/events/$id': typeof EventsIdRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/secret': typeof SecretRoute
  '/settings': typeof SettingsRoute
  '/world': typeof WorldRoute
  '/events/$id': typeof EventsIdRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRouteWithChildren
  '/friends': typeof FriendsRoute
  '/memories': typeof MemoriesRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/pro': typeof ProRoute
  '/profile': typeof ProfileRoute
  '/secret': typeof SecretRoute
  '/settings': typeof SettingsRoute
  '/world': typeof WorldRoute
  '/events/$id': typeof EventsIdRoute
  '/u/$handle': typeof UHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/auth'
    | '/events'
    | '/friends'
    | '/memories'
    | '/notifications'
    | '/post'
    | '/pro'
    | '/profile'
    | '/secret'
    | '/settings'
    | '/world'
    | '/events/$id'
    | '/u/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/auth'
    | '/events'
    | '/friends'
    | '/memories'
    | '/notifications'
    | '/post'
    | '/pro'
    | '/profile'
    | '/secret'
    | '/settings'
    | '/world'
    | '/events/$id'
    | '/u/$handle'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/auth'
    | '/events'
    | '/friends'
    | '/memories'
    | '/notifications'
    | '/post'
    | '/pro'
    | '/profile'
    | '/secret'
    | '/settings'
    | '/world'
    | '/events/$id'
    | '/u/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRouteWithChildren
  FriendsRoute: typeof FriendsRoute
  MemoriesRoute: typeof MemoriesRoute
  NotificationsRoute: typeof NotificationsRoute
  PostRoute: typeof PostRoute
  ProRoute: typeof ProRoute
  ProfileRoute: typeof ProfileRoute
  SecretRoute: typeof SecretRoute
  SettingsRoute: typeof SettingsRoute
  WorldRoute: typeof WorldRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret': {
      id: '/secret'
      path: '/secret'
      fullPath: '/secret'
      preLoaderRoute: typeof SecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRouteWithChildren,
  FriendsRoute: FriendsRoute,
  MemoriesRoute: MemoriesRoute,
  NotificationsRoute: NotificationsRoute,
  PostRoute: PostRoute,
  ProRoute: ProRoute,
  ProfileRoute: ProfileRoute,
  SecretRoute: SecretRoute,
  SettingsRoute: SettingsRoute,
  WorldRoute: WorldRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
